@host=http://localhost:5062

POST {{host}}/dinner
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTI1NGMxZi1hM2JkLTQ4MDQtYjRmYi03ZTczOWQ2NmUwZmUiLCJnaXZlbl9uYW1lIjoiSmFjb2IiLCJmYW1pbHlfbmFtZSI6IkxvcmVueiIsImp0aSI6ImMwOWMxOTZhLTM0Y2UtNGI5NC1iNGNhLTdjNTFmNWRkMTMzZSIsImF1ZCI6IkJ1YmVyRGlubmVyIiwiaXNzIjoiQnViZXJEaW5uZXIiLCJleHAiOjE3MTg1NTQwNzB9.w9BwPLBsAY1il-o3qyNW5fFAYmggcMe0U4Mp-O9bpoI